### ISSUE TITLE
ValueError: cannot reshape array of size 322560 into shape (1,newaxis,85)

### ISSUE THREAD

**Issue by aljohn0422** [TrojanXu/yolov5-tensorrt#10]
Firstly thanks for providing this great tool!

I tested this on Jetson Nano with Jetpack 4.4. I used yolov5s model. I followed your instructions by replacing all required fields (model names, nn.Upsample), but got this error: `ValueError: cannot reshape array of size 322560 into shape (1,newaxis,85)`

These are my package versions:
```
torch                         1.4.0a0+7f73f1d
torchvision                   0.5.0a0+85b8fbf
tensorrt                      7.1.0.16
onnx                          1.6.0
onnx-simplifier               0.2.9
```
A slightly detailed error message:
```
avg GPU time: 0.09655828211042616                                                     
avg GPU compute time: 0.09142438040839301                                             
avg pre time: 0.004831205474005805                                                    
avg post time: 0.00030269622802734373                                                 
Traceback (most recent call last):                                                    
  File "main.py", line 212, in <module>                                               
    trt_result = profile_trt(build_engine(onnx_path, using_half), batch_size, 10, 100)
  File "main.py", line 160, in profile_trt                                            
    return [np.array(yolo_outputs[0].host.reshape(1, -1, 85))]                        
ValueError: cannot reshape array of size 322560 into shape (1,newaxis,85)             
Segmentation fault (core dumped)                                                      
```

Any idea on what might caused this?

**Comment by TrojanXu** [comment]
have you changed numClass(nc) in yaml? the output should be times of [x,y,h,w,score,sub_class_scores]

**Comment by aljohn0422** [comment]
https://github.com/TrojanXu/yolov5-tensorrt/blob/f14394d0e96c8a00af61756603891c83509338e1/main.py#L160

This `85` should be changed to `numClass (read from yaml) + 5`

**Comment by pkraison** [comment]
Got it, thanks!
