### ISSUE TITLE
Getting KeyError issue  model.2.cv2.weight

### ISSUE THREAD

**Issue by muhammadabdullah34907** [TrojanXu/yolov5-tensorrt#11]
Installed exact same versions of dependencies but getting this keyerror issue.

Traceback (most recent call last):
  File "main.py", line 208, in <module>
    model = load_model()
  File "main.py", line 39, in load_model
    {k: v for k, v in ckpt['model'].state_dict().items() if model.state_dict()[k].numel() == v.numel()}
  File "main.py", line 39, in <dictcomp>
    {k: v for k, v in ckpt['model'].state_dict().items() if model.state_dict()[k].numel() == v.numel()}
KeyError: 'model.2.cv2.weight

**Comment by muhammadabdullah34907** [comment]
fixed. this is because original .pt model is updated.
