### ISSUE TITLE
How to solve cuda version conflict

### ISSUE THREAD

**Issue by hxk11111** [TrojanXu/yolov5-tensorrt#23]
The repository requires torch==1.4.0 + onnx==1.6.0 + TRT 7.0+ .

But torch 1.4.0 requires CUDA==10.1, TRT 7.0+ requires CUDA==10.0 or 10.2. 
How to solve this confliction? 

Hope someone could help

**Comment by TrojanXu** [comment]
Does torch report any error if you install 10.1-based package on server with cuda10.2

**Comment by hxk11111** [comment]
> Does torch report any error if you install 10.1-based package on server with cuda10.2

Thanks for your reply.
I tried to install torch==1.4.0, onnx==1.6.0 and TRT==7.0.0.11, and used python console to import all these packages, all of them worked fine.
But when I tried to run main.py in this repository, I got error like
```
[TensorRT] ERROR: CUDA initialization failure with error 35. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
Traceback (most recent call last):
  File "main.py", line 371, in <module>
    trt_result = profile_trt(build_engine(onnx_path, using_half), batch_size, 10, 100)
  File "main.py", line 164, in build_engine
    with trt.Builder(TRT_LOGGER) as builder, builder.create_network(EXPLICIT_BATCH) as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
TypeError: pybind11::init(): factory function returned nullptr
```
Do you have any hint about this? 

Thanks

**Comment by TrojanXu** [comment]
what's your driver? Is that sufficient for the CUDA version you use?
