### ISSUE TITLE
Node () has input size 5 not in range [min=1, max=1].

### ISSUE THREAD

**Issue by erdongchendou** [TrojanXu/yolov5-tensorrt#30]
When I ran 'python3 main.py', I got this error. Do you have any idea what is wrong?

```Traceback (most recent call last):
  File "main.py", line 369, in <module>
    simplify_onnx(onnx_path)
  File "main.py", line 154, in simplify_onnx
    model_simp, check = simplify(model)
  File "/home/nvidia/.local/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 300, in simplify
    onnx.checker.check_model(model)
  File "/home/nvidia/.local/lib/python3.6/site-packages/onnx/checker.py", line 86, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Node () has input size 5 not in range [min=1, max=1].

==> Context: Bad node spec: input: "data" input: "372" input: "373" input: "371" input: "374" output: "375" op_type: "Slice"```

**Comment by TrojanXu** [comment]
How about the versions of your python packages? I haven't run into this issue before.
