### ISSUE TITLE
KeyError: 'model.18.conv.weight'

### ISSUE THREAD

**Issue by llzhaoshuo** [TrojanXu/yolov5-tensorrt#39]
When I run python main.py , it shows:

Traceback (most recent call last):
  File "main.py", line 366, in <module>
    model = load_model()
  File "main.py", line 137, in load_model
    ckpt['model'] = {k: v for k, v in ckpt['model'].state_dict().items() if model.state_dict()[k].numel() == v.numel()}
  File "main.py", line 137, in <dictcomp>
    ckpt['model'] = {k: v for k, v in ckpt['model'].state_dict().items() if model.state_dict()[k].numel() == v.numel()}
KeyError: 'model.18.conv.weight'

In main.py , I have changed 'weights' ,'model_config' and 'image_loader',as follows:

device = torch_utils.select_device('0')
weights = './ylov5s-best.pt'
model_config = './yolov5s.yaml'
TRT_LOGGER = trt.Logger(trt.Logger.INFO)
EXPLICIT_BATCH = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
image_loader = LoadImages('yolov5/inference/images', img_size=512)
image_loader.__iter__()
_, input_img, _, _ = image_loader.__next__()
input_img = input_img.astype(np.float)
input_img /= 255.0
input_img = np.expand_dims(input_img, axis=0)
with open(model_config) as f:
    cfg = yaml.load(f, Loader=yaml.FullLoader)  # model dict
    num_classes = cfg['nc']

**Comment by TrojanXu** [comment]
is ylov5s-best.pt aligned with yolov5s.yaml? And by the way, is there a typo here in ylov5s-best.pt？
