### ISSUE TITLE
NameError: name 'Focus' is not defined

### ISSUE THREAD

**Issue by Yang-Changhui** [TrojanXu/yolov5-tensorrt#40]
Traceback (most recent call last):
  File "main.py", line 367, in <module>
    model = load_model()
  File "main.py", line 135, in load_model
    model = Model(model_config).to(device)
  File "/home/boyt/yolov5-tensorrt-master/yolo.py", line 74, in __init__
    self.model, self.save = parse_model(self.md, ch=[ch])  # model, savelist, ch_out
  File "/home/boyt/yolov5-tensorrt-master/yolo.py", line 173, in parse_model
    m = eval(m) if isinstance(m, str) else m  # eval strings
  File "<string>", line 1, in <module>
NameError: name 'Focus' is not defined
I hope someone can tell me how to slove it .Thanks

**Comment by TrojanXu** [comment]
Have you run git submodule update --init to download yolov5 repo?
